spring:
  application:
    name: auth-service

  #DB configuration
  datasource:
    url: jdbc:mysql://localhost:3306/authDB
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: false

    properties:
      hibernate:
        format_sql: false

#Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  servlet:
    context-path: /auth

  port: 9010

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      userRetry:
        maxAttempts: 5
        waitDuration: 15s

  ratelimiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod: 5s
        limitForPeriod: 10
        timeoutDuration: 1s

  circuitbreaker:
    instances:
      userCircuitBreaker:
        registerHealthIndicator: true #Expose circuit breaker health via the actuator
        slidingWindowSize: 10 #Size of the sliding window for call recording
        slidingWindowType: COUNT_BASED #User count-based sliding window
        minimumNumberOfCalls: 10 #Minimum number of calls before calculating failure rate
        failureRateThreshold: 50 #If 50% (5 out of 10) calls fail, the circuit goes to OPEN state
        waitDurationInOpenState: 20s #Time the stays OPEN before moving to HALF_OPEN
        permittedNumberOfCallsInHalfOpenState: 3 #Number of test calls in HALF_OPEN state
        eventConsumerBufferSize: 10 #Buffer size for event lags